name: magic_alumni
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  stacked_services: ^1.6.0
  stacked: ^3.4.4
  flutter_dotenv: ^5.2.1
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.2
  encrypt: ^5.0.3
  intl: ^0.20.2
  url_launcher: ^6.3.1
  infinite_scroll_pagination: ^4.1.0
  firebase_core: ^3.10.1
  onesignal_flutter: ^5.3.0
  sqflite: ^2.4.1
  razorpay_flutter: ^1.4.0
  pay: ^3.1.0
  mockito: ^5.4.5
  permission_handler: ^12.0.0+1
  sms_autofill: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  stacked_generator: ^1.6.1
  # flutter_launcher_icons: ^0.14.2

#  To generate the laucher_icon file run the following command in the terminal `dart run flutter_launcher_icons`
# flutter_launcher_icons:
#   android: 'launcher_icon'
#   ios: true
#   image_path: "assets/icon/icon.png"
flutter:
  uses-material-design: true
  assets:
    # - .env
    - assets/icon/
    - assets/bottom/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
